const express = require('express')

const router = express.Router()

const userSignUpController = require("../controller/user/userSignUp")
const userSignInController = require('../controller/user/userSignIn')
const userDetailsController = require('../controller/user/userDetail')
const authToken = require('../middleware/authToken')
const userLogout = require('../controller/user/userLogout')
const allUser = require('../controller/user/allUser')
const updateUser = require('../controller/user/updateUser')
const UploadPrpductController = require('../controller/product/uploaadProduct')
const getProductController = require('../controller/product/getProduct')
const updateProductController = require('../controller/product/updateProduct')
const getCategoryProduct = require('../controller/product/getCategoryProduct')
const getCategoryWiseProduct = require('../controller/product/getCategoryWiseProduct')
const getProductDetailsController = require('../controller/product/getProductDetail')
const addToCartController = require('../controller/user/addToCart')
const countAddToCart = require('../controller/user/countProductAddToCart')
const addToCartViewProduct = require('../controller/user/addToCartViewProduct')
const updateAddToCartProduct = require('../controller/user/updateAddToCart')
const deleteProduct = require('../controller/user/deleteProduct')
const SearchProduct = require('../controller/product/searchProduct')
const filterProduct = require('../controller/product/filterProduct')
const placeOrder = require('../controller/user/orderProduct')
const verifyOrder = require("../controller/user/verifyOrder")
const userOrders = require("../controller/user/userorder")
const listOrders = require('../controller/user/listOrder')
const updateStatus = require('../controller/user/updateStatus')
const sendEmail = require('../controller/user/sendEmail')
const allOrder = require('../controller/user/allOrder')
const getReviewProduct = require('../controller/user/getReviewProduct')
const postReviewProduct = require('../controller/user/postReviewProduct')
const sendOrderItem = require('../controller/user/sendOrderItem')
const getOrderItem = require('../controller/user/getOrderItem')
const listLikeProduct = require('../controller/user/listLike')
const listLikeView = require('../controller/user/listLikeView')
const countProductFavorite = require('../controller/user/countProductFavorite')
const deleteFavoriteProduct = require('../controller/user/deleteFavoriteProduct')
const userConfirmController = require('../controller/user/userConfirmController')
const forgotPassword = require('../controller/user/forgotPassword')
const resetPassword = require('../controller/user/resetPassword')
router.post("/signup", userSignUpController)
router.get('/confirm/:token', userConfirmController);
router.post("/signin", userSignInController)
router.get("/user-details", authToken, userDetailsController)
router.get("/userLogout", userLogout)
// admin panel
router.get("/all-user", authToken, allUser)
router.post("/update-user", authToken, updateUser)

//product
router.post("/upload-product", authToken, UploadPrpductController)
router.get("/get-product", getProductController)
router.post("/update-product", authToken, updateProductController)
router.get("/get-categoryProduct", getCategoryProduct)
router.post("/category-product", getCategoryWiseProduct)
router.post("/product-details", getProductDetailsController)
router.get("/search", SearchProduct)
router.post("/filter-product", filterProduct)
// user add to cart
router.post("/addtocart", authToken, addToCartController)
router.get("/countAddToCartProduct", authToken, countAddToCart)
router.get("/view-cart-product", authToken, addToCartViewProduct)
router.post("/update-cart-product", authToken, updateAddToCartProduct)
router.post("/delete-cart", authToken, deleteProduct)
router.post("/place", authToken, placeOrder)
router.post("/verify", verifyOrder)
router.get("/userorders", authToken, userOrders)
// router.get("/list", listOrders)
router.post("/status", updateStatus)

router.post("/send-email", sendEmail)
router.get("/all-order", allOrder)

router.post("/productId", getReviewProduct)
router.post("/review", authToken, postReviewProduct)

router.post("/orderitem", sendOrderItem)
router.post("/order-detail", getOrderItem)

router.post("/favorite",authToken,listLikeProduct)
router.post("/listfavorite",authToken,listLikeView)
router.get("/count-favorite",authToken,countProductFavorite)
router.post("/deletefavorite",authToken,deleteFavoriteProduct)


router.post("/forgot-password",forgotPassword)
router.post('/reset-password/:token',resetPassword)
module.exports = router